///////////////////////////////////////////////////////////
//  ConstraintField.cs
//  Implementation of the Class ConstraintField
//  Generated by Enterprise Architect
//  Created on:      14-set-2006 01:17:11
//  Original author: Fábio Nuno
///////////////////////////////////////////////////////////
using System;
using System.Text;
namespace Ag2.Manager.Module 
{
	/// <summary>
	/// Campos que serão verificandos em uma Constraint
	/// </summary>
	public class ConstraintField {

		/// <summary>
		/// Nome do campo que o sistema utilizara para fazer a constraint na consulta SQL.
		/// Utilizado em casos que a query montado utiliza ALIAS para o nome da tabela,
		/// logo o campo que sera utilizado na verificação será [TABELA ou ALIAS].[NOME DO
		/// CAMPO].
		/// Se esse valor não for informado será utilizando o campo dataFieldName da
		/// interface IModuleField
		/// </summary>
		private string _dbFieldName;
		/// <summary>
		/// Campo do modulo a que a constraint se refere
		/// </summary>
		private ManagerModuleField _field;

		public ConstraintField(){

        }


        #region PROPERTY
        /// <summary>
		/// Nome do campo que o sistema utilizara para fazer a constraint na consulta SQL.
		/// Utilizado em casos que a query montado utiliza ALIAS para o nome da tabela,
		/// logo o campo que sera utilizado na verificação será [TABELA ou ALIAS].[NOME DO
		/// CAMPO].
		/// Se esse valor não for informado será utilizando o campo dataFieldName da
		/// interface IModuleField
		/// </summary>
		public string DbFieldName {
			get{
                //if dataFieldName not informed in constraint
                //get it from property dataFieldName of field
                if (String.IsNullOrEmpty(_dbFieldName))
                {
                    return _field.DataFieldName;
                } else {
				    return _dbFieldName;
                }
			}
			set{
				_dbFieldName = value;
			}
		}

		/// <summary>
		/// Campo do modulo a que a constraint se refere
		/// </summary>
		public ManagerModuleField Field{
			get{
				return _field;
			}
			set{
				_field = value;
			}
        }
        #endregion

    }//end ConstraintField

}//end namespace Module