///////////////////////////////////////////////////////////
//  ConstraintType.cs
//  Implementation of the Class ConstraintType
//  Generated by Enterprise Architect
//  Created on:      14-set-2006 01:17:12
//  Original author: Fábio Nuno
///////////////////////////////////////////////////////////

namespace Ag2.Manager.Module {
	public enum ConstraintType : int {

		/// <summary>
		/// O valor do campo deve ser unico na base
		/// </summary>
		Unique = 0

	}//end ConstraintType

}//end namespace Module